#!/usr/bin/env bash
# Set up Load balancer on two websites usng Haproxy
sudo apt-get -y update && sudo apt-get -y install haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1/g" /etc/default/haproxy
sudo sed -i "\$ a\listen 349-lb-01\n\tbind *:80\n\tmode http\n\tstats enable\n\tbalance roundrobin\n\tserver 1071-web-01 35.196.35.132:80 check\n\tserver 1071-web-02 18.207.115.227:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start