#!/usr/bin/env bash
# Debug NGINX server to listen to prot 80

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
pkill -f -SIGKILL  "/usr/sbin/nginx"
