#!/usr/bin/env bash
#Script to display username user id home dir path for the user of the content of the file /etc/passwd

filename="/etc/passwd"

while read line
do
      echo "$line" | cut -d':' -f 1,3,6
done < $filename