#!/usr/bin/env bash
# Script to display 'bad luck' when 4, 'good luck' when 8 else 'Holberton School'
i=1
while ((i < 11))
do
      if (( i == 4))
      then
	  echo "bad luck"

      elif ((i == 8))
      then
	  echo "good luck"
      else
	  echo "Holberton School"
      fi
      i=$((i + 1))
done
